### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Kl0udY** [Kl0udY/protospace-37839#1]
https://protospace-37839.herokuapp.com/

**Comment by shodai-ito** [comment]
@Kl0udY さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
`コメント機能`
- [ ] **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
空のフォームを投稿するとエラーになります。

`ユーザー詳細機能`
- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
プロトタイプ詳細ページの投稿者、コメントの投稿者をクリックした際に意図したユーザーの詳細ページに遷移できません。


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Kl0udY** [comment]
修正しました。ご確認よろしくお願いします。

https://protospace-37839.herokuapp.com/

**Comment by yusuketono** [comment]
@Kl0udY さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
